#!/usr/bin/env python3
"""Phase 2 smoke tests: dedupe + sanity check + Day MOC generation.

No external deps beyond the script's own (yaml). No Haiku/API calls — uses --no-ai.
Run:
    python3 tests/test_phase2_dedupe_and_mocs.py
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "build_obsidian_vault.py"
PY = sys.executable


def make_lesson(lesson_dir: Path, lesson_id: str, title: str, lesson_index: int,
                module_index: int, module_title: str, has_video: bool = False) -> None:
    lesson_dir.mkdir(parents=True, exist_ok=True)
    meta = {
        "lessonId": lesson_id,
        "title": title,
        "lessonIndex": lesson_index,
        "moduleIndex": module_index,
        "moduleTitle": module_title,
        "hasVideo": has_video,
    }
    (lesson_dir / "lesson.json").write_text(json.dumps(meta), encoding="utf-8")
    # Provide a small index.html so the lesson is scannable without a transcript.
    (lesson_dir / "index.html").write_text(
        f"<html><body><div class='content'><h1>{title}</h1><p>Body.</p></div></body></html>",
        encoding="utf-8",
    )


def run_script(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [PY, str(SCRIPT), *args],
        capture_output=True, text=True, cwd=REPO,
    )


def test_sanity_check_blocks_duplicated_vault() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        # resolve() to bypass macOS /var → /private/var symlink that breaks .relative_to()
        root = Path(tmp).resolve() / "fakevault"
        (root / "fakevault").mkdir(parents=True)  # nested same-name dir = duplication signal
        r = run_script(str(root), "--no-ai", "--dry-run")
        assert r.returncode == 2, f"expected exit 2, got {r.returncode}\nstderr: {r.stderr}"
        assert "Vault duplication detected" in r.stderr, f"missing message in: {r.stderr}"
    print("PASS: sanity check exits 2 on duplicated vault")


def test_dedupe_skips_duplicate_lesson_id() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve() / "vault"
        # two physically separate lesson dirs with the SAME lesson_id
        make_lesson(root / "Month 1" / "1-Day 1" / "01-foo", "LID-A", "Foo", 1, 1, "Day 1")
        make_lesson(root / "Month 1" / "1-Day 1" / "02-foo-dup", "LID-A", "Foo Dup", 2, 1, "Day 1")
        make_lesson(root / "Month 1" / "1-Day 1" / "03-bar", "LID-B", "Bar", 3, 1, "Day 1")
        r = run_script(str(root), "--no-ai")
        assert r.returncode == 0, f"exit {r.returncode}\nstderr: {r.stderr}\nstdout: {r.stdout}"
        assert "duplicate lesson_id" in r.stderr, f"no dedupe warning: {r.stderr}"
        assert "found 2 lessons" in r.stdout, f"expected 2 unique lessons: {r.stdout}"
    print("PASS: dedupe skips duplicate lesson_id, keeps first")


def test_day_moc_generation_and_auto_note() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve() / "vault"
        make_lesson(root / "Month 1" / "1-Day 1" / "01-a", "L1", "A", 1, 1, "Day 1")
        make_lesson(root / "Month 1" / "1-Day 1" / "02-b", "L2", "B", 2, 1, "Day 1")
        make_lesson(root / "Month 1" / "2-Day 2" / "01-c", "L3", "C", 1, 2, "Day 2")
        # Empty module dir (no lessons) — should still get a stub MOC from FS sweep.
        (root / "Month 1" / "3-Day 3").mkdir(parents=True)
        r = run_script(str(root), "--no-ai")
        assert r.returncode == 0, f"exit {r.returncode}\n{r.stderr}\n{r.stdout}"
        moc1 = root / "Month 1" / "1-Day 1" / "_Day 1.md"
        moc2 = root / "Month 1" / "2-Day 2" / "_Day 2.md"
        moc3 = root / "Month 1" / "3-Day 3" / "_Day 3.md"  # fs-sweep stub
        assert moc1.exists() and moc2.exists(), f"missing module MOCs"
        assert moc3.exists(), "fs-sweep MOC for empty module not generated"
        body1 = moc1.read_text(encoding="utf-8")
        assert "moc_type: module" in body1, f"missing moc_type: {body1[:300]}"
        assert "course: Month 1" in body1, f"wrong course (expected section name): {body1[:300]}"
        assert "auto-generated by build_obsidian_vault.py" in body1, "missing auto-note"
        # Lessons listed in index order
        idx_a = body1.find("01. A")
        idx_b = body1.find("02. B")
        assert 0 < idx_a < idx_b, f"lessons out of order: {body1}"
    print("PASS: Day MOCs written with moc_type, course-from-section, auto-note, ordered links")


def test_course_from_section_default_vs_off() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve() / "MyVault"
        make_lesson(root / "Month 1" / "1-Day 1" / "01-a", "L1", "A", 1, 1, "Day 1")
        # default: course = section name = "Month 1"
        r = run_script(str(root), "--no-ai")
        assert r.returncode == 0, r.stderr
        lesson_md = next((root / "Month 1" / "1-Day 1").rglob("01. A.md"))
        assert "course: Month 1" in lesson_md.read_text(encoding="utf-8")
        # legacy: course = vault_root.name = "MyVault"
        shutil.rmtree(root)
        make_lesson(root / "Month 1" / "1-Day 1" / "01-a", "L1", "A", 1, 1, "Day 1")
        r = run_script(str(root), "--no-ai", "--no-course-from-section")
        assert r.returncode == 0, r.stderr
        lesson_md = next((root / "Month 1" / "1-Day 1").rglob("01. A.md"))
        assert "course: MyVault" in lesson_md.read_text(encoding="utf-8")
    print("PASS: --course-from-section toggles section vs vault_root.name")


def test_orphan_section_level_moc_cleaned() -> None:
    """Pre-consolidation builds wrote module MOCs at section level
    (e.g. Month 1/_Day 3.md). The build should detect & remove these."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve() / "vault"
        make_lesson(root / "Month 1" / "1-Day 1" / "01-a", "L1", "A", 1, 1, "Day 1")
        # Plant a stale section-level MOC with module-moc frontmatter.
        orphan = root / "Month 1" / "_Day 3.md"
        orphan.parent.mkdir(parents=True, exist_ok=True)
        orphan.write_text(
            "---\nvault_schema: 1\ntitle: Day 3\ntype: module-moc\ncourse: Month 1\nmodule: Day 3\n---\n# Day 3\n",
            encoding="utf-8",
        )
        r = run_script(str(root), "--no-ai")
        assert r.returncode == 0, f"exit {r.returncode}\n{r.stderr}\n{r.stdout}"
        assert not orphan.exists(), f"orphan section-level MOC was not removed: {orphan}"
        # Sibling course MOC must NOT be removed (it lives at section level too).
        course_moc = root / "Month 1" / "_Month 1.md"
        assert course_moc.exists(), "course MOC erroneously removed"
        assert "removed" in r.stdout, f"no removal message in stdout: {r.stdout}"
    print("PASS: orphan section-level module-moc cleaned, course MOC preserved")


def test_concept_stub_case_insensitive_dedupe() -> None:
    """Two lessons with same concept in different casings must produce ONE
    stub (first-seen casing wins) — prevents case-collision data loss on
    case-insensitive filesystems (macOS/Windows)."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve() / "vault"
        # Lesson A uses "Simplicity As Value", Lesson B uses "Simplicity as Value".
        # Write the pre-tagged note at the renamed location ("NN. Title.md") so the
        # scanner picks it up as the existing transcript and --no-ai pulls concepts
        # from frontmatter (instead of falling through to sparse derivation).
        for lid, idx, name, concept in [
            ("LA", 1, "A", "Simplicity As Value"),
            ("LB", 2, "B", "Simplicity as Value"),
        ]:
            ldir = root / "Month 1" / "1-Day 1" / f"0{idx}-{name.lower()}"
            ldir.mkdir(parents=True, exist_ok=True)
            (ldir / "lesson.json").write_text(
                json.dumps({
                    "lessonId": lid, "title": name, "lessonIndex": idx,
                    "moduleIndex": 1, "moduleTitle": "Day 1", "hasVideo": False,
                }), encoding="utf-8")
            # Fat body → bypasses sparse-derivation path; with backend=none the
            # script falls through to the fm-based assignment (L586-587).
            big = ("This is body content used to exceed the sparse input threshold. " * 10)
            (ldir / "index.html").write_text(
                f"<html><body><div class='content'><h1>{name}</h1><p>{big}</p></div></body></html>",
                encoding="utf-8")
            note = ldir / f"0{idx}. {name}.md"
            note.write_text(
                "---\n"
                "vault_schema: 1\n"
                f"title: {name}\n"
                "course: Month 1\n"
                "module: Day 1\n"
                "module_index: 1\n"
                f"lesson_index: {idx}\n"
                f"lesson_id: {lid}\n"
                "tags:\n- t\n"
                f"concepts:\n- {concept}\n"
                "summary: x\n"
                "body_sha: deadbeef\n"
                "---\n"
                f"# {name}\n\n## Transcript\n\n{big}\n",
                encoding="utf-8",
            )
        r = run_script(str(root), "--no-ai")
        assert r.returncode == 0, f"exit {r.returncode}\n{r.stderr}\n{r.stdout}"
        stubs = list((root / "Concepts").glob("Simplicity*Value*.md"))
        assert len(stubs) == 1, f"expected exactly 1 stub, got {len(stubs)}: {[s.name for s in stubs]}"
        # First-seen casing (lesson_index=1 = "Simplicity As Value") wins.
        assert stubs[0].name == "Simplicity As Value.md", f"unexpected casing: {stubs[0].name}"
    print("PASS: concept stub case-insensitive dedupe (first-seen casing wins)")


if __name__ == "__main__":
    tests = [
        test_sanity_check_blocks_duplicated_vault,
        test_dedupe_skips_duplicate_lesson_id,
        test_day_moc_generation_and_auto_note,
        test_course_from_section_default_vs_off,
        test_orphan_section_level_moc_cleaned,
        test_concept_stub_case_insensitive_dedupe,
    ]
    failures = 0
    for t in tests:
        try:
            t()
        except AssertionError as e:
            failures += 1
            print(f"FAIL: {t.__name__}: {e}", file=sys.stderr)
        except Exception as e:
            failures += 1
            print(f"ERROR: {t.__name__}: {e!r}", file=sys.stderr)
    if failures:
        print(f"\n{failures}/{len(tests)} tests failed", file=sys.stderr)
        sys.exit(1)
    print(f"\n{len(tests)}/{len(tests)} tests passed")
